backend:
  name: github
  repo: lhabro/mongoliantravel
  branch: main
  base_url: https://mongoliantravel.xyz
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Нийтлэлүүд"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Гарчиг (Монгол)", name: "title_mn", widget: "string"}
      - {label: "Гарчиг (Англи)", name: "title_en", widget: "string"}
      - {label: "Ангилал", name: "category", widget: "select", options: ["Аялал", "Хоол", "Амьдрал"]}
      - {label: "Огноо", name: "date", widget: "datetime"}
      - {label: "Агуулга (Монгол)", name: "body_mn", widget: "markdown"}
      - {label: "Агуулга (Англи)", name: "body_en", widget: "markdown"}
